"""add username profile_pic and onboarding columns

Revision ID: aec690e396d0
Revises: 9e5aaa88afc5
Create Date: 2026-09-09 10:20:37.926505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aec690e396d0'
down_revision: Union[str, Sequence[str], None] = '9e5aaa88afc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('profile_pic_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('onboarding', sa.Boolean(), server_default='false', nullable=False))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'onboarding')
    op.drop_column('users', 'profile_pic_url')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
